# -*- coding: utf-8 -*-
"""brainTumor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qlaJVtyMtv4SImA0o2mUVuuiPiBi5DKp
"""

import os
import zipfile
import shutil
import numpy as np
import matplotlib.pyplot as plt
from glob import glob
from tqdm import tqdm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc
import seaborn as sns

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms, models


#extracting the zip file from google drive
from google.colab import drive

from google.colab import drive
drive.mount('/content/drive')

zip_path = '/content/drive/MyDrive/Colab Notebooks/archive.zip'
extract_dir = '/content/Archive'
dataset_root = "/content/Archive"
train_dir = os.path.join(dataset_root, "Training")
test_dir = os.path.join(dataset_root, "Testing")

# Unzip the data
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_dir)

def separate_as_binary(source_dir, benign_dir, malignant_dir):
    os.makedirs(benign_dir, exist_ok=True)
    os.makedirs(malignant_dir, exist_ok=True)

    for subfolder in os.listdir(source_dir):
        full_subdir = os.path.join(source_dir, subfolder)
        if not os.path.isdir(full_subdir):
            continue

        category = subfolder.lower()
        if "no" in category:  # e.g., no_tumor
            target_dir = benign_dir
        else:
            target_dir = malignant_dir

        for img_path in glob(os.path.join(full_subdir, "*.jpg")):
            shutil.copy(img_path, target_dir)

    print(f"Separated images in {source_dir} into benign and malignant folders.")

# Set binary class folders
train_benign = "/content/Archive/BinaryTrain/Benign"
train_malignant = "/content/Archive/BinaryTrain/Malignant"

test_benign = "/content/Archive/BinaryTest/Benign"
test_malignant = "/content/Archive/BinaryTest/Malignant"

# Separate into binary classes
separate_as_binary(train_dir, train_benign, train_malignant)
separate_as_binary(test_dir, test_benign, test_malignant)

os.makedirs("/content/Archive/Training/Tumor", exist_ok=True)
os.makedirs("/content/Archive/Training/NonTumor", exist_ok=True)
os.makedirs("/content/Archive/Testing/Tumor", exist_ok=True)
os.makedirs("/content/Archive/Testing/NonTumor", exist_ok=True)

# Then call your separation function:
separate_as_binary(train_dir,
                "/content/Archive/Training/Tumor",
                "/content/Archive/Training/NonTumor")

separate_as_binary(test_dir,
                "/content/Archive/Testing/Tumor",
                "/content/Archive/Testing/NonTumor")

# Define device (GPU if available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Model Definition (using ResNet-50 as an example)
model = models.resnet50(pretrained=True)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(model.fc.in_features, 2)  # 2 classes: Tumor and NonTumor
model = model.to(device)

# Data Transforms and Dataloader
transform = transforms.Compose([
    transforms.Resize((224, 224)),  # Resize images to fit the model input
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])  # Pretrained mean and std
])

binary_train_dir = "/content/Archive/BinaryTrain"
binary_test_dir = "/content/Archive/BinaryTest"
train_data = datasets.ImageFolder(binary_train_dir, transform=transform)
test_data = datasets.ImageFolder(binary_test_dir, transform=transform)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader = DataLoader(test_data, batch_size=32, shuffle=False)

#training the model
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4, momentum=0.9)

# Training loop
def train_model(model, train_loader, criterion, optimizer, epochs=5):
    model.train()
    for epoch in range(epochs):
        running_loss = 0.0
        correct = 0
        total = 0
        for images, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}"):
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

        print(f"Loss: {running_loss:.4f}, Accuracy: {100*correct/total:.2f}%")

        train_model(model, train_loader, criterion, optimizer)

# Evaluation
model.eval()
all_preds = []
all_probs = []
all_labels = []

with torch.no_grad():
    for images, labels in tqdm(test_loader, desc="Evaluating"):
        images = images.to(device)
        outputs = model(images)
        probs = outputs.cpu().numpy()
        preds = np.argmax(probs, axis=1)

        all_preds.extend(preds)
        all_probs.extend(probs[:, 1])  # Probability of class 1
        all_labels.extend(labels.numpy())

# Accuracy
accuracy = np.mean(np.array(all_preds) == np.array(all_labels))
print(f"Test Accuracy: {accuracy:.4f}")

conf_mat = confusion_matrix(all_labels, all_preds)
print("Confusion Matrix:\n", conf_mat)
plt.figure()
sns.heatmap(conf_mat, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

# ROC Curve
fpr, tpr, _ = roc_curve(all_labels, all_probs)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, color="darkorange", lw=2, label=f"ROC curve (AUC = {roc_auc:.2f})")
plt.plot([0, 1], [0, 1], color="navy", lw=2, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Receiver Operating Characteristic")
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

epoch_losses, epoch_accuracies = train_model(model, train_loader, criterion, optimizer, epochs=5)

# Plot learning curves
plt.figure(figsize=(12, 5))

# Loss curve
plt.subplot(1, 2, 1)
plt.plot(epoch_losses, label="Loss", marker='o')
plt.title("Training Loss per Epoch")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.grid(True)

# Accuracy curve
plt.subplot(1, 2, 2)
plt.plot([a * 100 for a in epoch_accuracies], label="Accuracy", color='green', marker='o')
plt.title("Training Accuracy per Epoch")
plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.grid(True)

plt.tight_layout()
plt.show()